### ISSUE TITLE
upload capacitive sensor test code to this arduino-scripts

### ISSUE THREAD

**Issue by M-LKT** [LiquidPropulsionGroup/arduino-scripts#2]
@TWCCarlson please upload the Arduino code that you made to this repo as we are branching it out from RocketConfigurationVisualizer, which will be design code only.

**Comment by TWCCarlson** [comment]
Everything used in the creation of the capacitor test was removed from RocketConfigurationVisualizer and placed inside arduino-scripts/capacitor-test.
